### ISSUE TITLE
[Suggestion] Add Riot to Community List

### ISSUE THREAD

**Issue by asddsaz** [minetest/minetest.github.io#136]
Currently when you click "community" on "minetest.net" it just has "Overview", "Forum", "Wiki", "IRC", "Subreddit", "Contributor" and, "Server list". I would stand to say that RIOT has a much broader community and better UI than IRC. I recommend adding it as a community option alongside the [IRC Riot Bridge](https://about.riot.im/apps-bots-and-bridges/).

Minetest Riot/Matrix Channel: #minetest-matrix:matrix.org

Riot: https://riot.im/

**Comment by benrob0329** [comment]
I would definitely say that a client for a decentralized JSON based protocol has a much better UI than a raw text based protocol, however thats not really a fair comparison.

Riot's UI is a mess atm, but there are other clients. Hexchat's UI is a bit dated, but again there are other clients. It all comes down to the application, not so much the underlying protocol.

The website should only give links to official groups IMHO, which a Matrix Room could become but I don't see it happening since much of the community and devs are happy on IRC.

Disclaimer: I administrate several Matrix rooms, including one for Minetest. Have used it on and off for over a year (or two, idr) now, and am aware of a decently sized protocol fork taking place.

**Comment by asddsaz** [comment]
@benrob0329 IMO the underlying difference is that IRC is text only.

> The website should only give links to official groups IMHO, which a Matrix Room could become but I don't see it happening since much of the community and devs are happy on IRC.

Ya, so the many of the people playing Minetest are gamers not devs. And in my experience next to no gamers use IRC. They love MEMEs and Emojis to much. IRC just can't handle that. :(

Also, I'm not saying to get rid of IRC, you can keep that. I just wouldn't have thought it to be the "best foot" to put forward.

**Comment by sofar** [comment]
The developers are on IRC. Not just a few. All of them. They will likely always be there, since freenode is the one and only place where OSS developers can collaborate in realtime. Remember that most of the Minetest devs have other OSS projects that they collaborate on. Maybe not as much as some others, but it matters. They won't ever get that level of cross OSS project community that FreeNode has anywhere else.

And, since it's the developers that create Minetest, they're going to stay there, and they want, and need, new developers to be able to find them and talk about development of minetest code, games, and other stuff.

For this reason alone, I have no issues with gamers making a gamers-only environment. But you will never attract developers to it, and it will never result in a true dialogue between players and developers.

So, if you want to break up the "circle jerk" of developers, you have to bring the gamers to IRC.

If you don't want that, go ahead and have fun with other gamers on whatever non-IRC platform you want to enjoy.

But IRC needs to remain a top mention. After all, without developers, the game wouldn't have existed, and we want the game to continue to evolve.

Matrix, slack, discord, and all the other stuff is cute and I have no issues with listing. But IRC is, and will remain, more important than the others.

**Comment by asdfghjz** [comment]
**Also for the love of all that is good in this world do not bridge things using the Matrix.org bridges. They have a terrible habit of taking down the whole network.**

I believe they fixed this in the last release.

**Matrix, slack, discord, and all the other stuff is cute and I have no issues with listing. But IRC is, and will remain, more important than the others.**
 
I agree. As the author stated, I believe it would be great to utilize one of the IRC / Matrix Bots/Bridges. The gamers get to stay where they are and the devs where they are.

**Comment by sfan5** [comment]
Bridges are terrible. Whichever side has less users and/or the platform with less features is treated as "second class citizens".
