### ISSUE TITLE
Add Existing Dev Donation/Patreon Pages To The "Donations" Section

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest.github.io#222]
We have a donations section, some people _do_ wish to donate, and to my knowledge both rubenwardy and paramat have Patreon pages. It only seems fitting to pad out this section with that information.

**Comment by Mte90** [comment]
Any updates for this? After the discussion on https://www.reddit.com/r/opensource/comments/rrzg6g/italian_linux_society_donated_9000_to_foss/hqjrcit/?context=3 I think that is important that this page is improved to avoid this confusion.

**Comment by celeron55** [comment]
I came to write an issue about this but low and behold, there it is already. This is a complex situation and I'm not a good storyteller, but I'll try to describe it.

Minetest does not have a non-profit organization. The reason is, I don't like running such organizations, making someone else to run such a thing would cost more than the value of donations usually is, and due to attacks towards community members by a hostile party, most members including me want to stay as anonymous as possible. It is not possible to set up a non-profit organization without releasing a lot of personal information, handily being available for doxxing, fake accusations to your employer and whatnot. The stuff that would happen is literally terrifying. For this reason, we can only accept donations personally.

Currently, I am the only person mentioned on the donation section. I trust the core team to speak up to me if they are not happy with the situation, and it has not happened. I make it clear what I use donations for, and so far donations have never exceeded what is reasonable for those uses. Again, I trust the core team to raise the topic towards me when necessary, which has not happened.

We have a team that specializes in administrative tasks called the Minetest Staff which was formed years ago organically from forum moderators, those hosting official-ish servers and doing administrative tasks. (if you do "Staff stuff" and aren't invited to the IRC channel, /msg me) The linux.it donation was discussed there yesterday. Present was sfan5, rubenwardy and myself, and we agreed for now I will allocate it towards long term hosting expenses (just like is stated on the donation page and on my liberapay page), and if more such donations pop up it will be discussed again.

Many core devs do not want to be mentioned on the donations section. I discussed this rubenwardy and sfan5. Their respective statements were "My patreon covers all my Minetest costs already" and "[would I like to be mentioned on minetest.net] as people to donate to? not really".

Thus I propose two alternative solutions:

1) We keep it as it is, just adding a link to this issue. People donating can view this issue, which explains the situation and has public comments from the core team that are in agreement.

2) We add a list of those core team members who would like to receive donations, with each having a description of what their use case for donations is, and a link where to donate. And of course link this issue.

Thus, I would like the core team and staff to either agree with the current donation section, or to request themselves to be added, listing the required information for the addition.

**Comment by SmallJoker** [comment]
> \<Krock\> I can provide my two cents, but it won't help any further. I do not care about donations.

:point_up:

**Comment by v-rob** [comment]
Personally, donations aren't a big deal to me one way or another.  I appreciate anyone who would want to donate money to me for my development work, but it's not really a motivating factor for me, so I've never taken the trouble to find a donation platform and set up an account.  I think I trust c55 enough when he says that donations just go to hosting costs and nothing else really.

**Comment by lhofhansl** [comment]
Happy with (1)
I work on this for the fun of writing some code, I'd prefer not be mentioned as possible recipient of donations.
