### ISSUE TITLE
switching to gulp?

### ISSUE THREAD

**Issue by est31** [minetest/minetest.github.io#29]
@Calinou has said in IRC:
```
<Calinou> 	I successfully learned Gulp, maybe minetest.net will use it in some time.
<Calinou> 	I have a really good workflow set up here: https://gist.github.com/Calinou/3cd3d529a6d3dabb911e
<Calinou> 	but it does not work on Windows (ENOENT error on "spawn jekyll"), even though Jekyll is installed and in PATH
```
So, I wonder, what is gulp, what are the advantages over current useage, should we switch?

**Comment by Calinou** [comment]
I believe gulp has several advantages over Grunt:

- slightly faster
- better console output (more detailed than Grunt, yet concise)
- configuration file is better designed

However, if we want to automate everything using a single command (ie. making `jekyll serve` obsolete), then Windows support must be fixed. It'll also imply Browsersync will be used (since one needs to run a local server in order to view the pages properly), which seems to require a large dependency on Windows (Visual Studio Community).

**Comment by rubenwardy** [comment]
The only reason why we need Grunt or Gulp is because we use Stylus. If we switch to SCSS then we wouldn't need either, as SCSS is supported by Jekyll.

**Comment by ShadowNinja** [comment]
Implemented rubenwardy's suggestion in #40.

**Comment by neoascetic** [comment]
Really? Why have all this stuff for static with such simple design?

**Comment by ShadowNinja** [comment]
@neoascetic: Huh?  What are you saying?  Anyways, I guess this should be closed.
