### ISSUE TITLE
Ubuntu downloads - linking to ubuntu appdb?

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest.github.io#45]
Since Minetest 0.4.13, the ubuntu download page (stable) has linked to http://packages.ubuntu.com/search?keywords=minetest, rather than https://code.launchpad.net/~minetestdevs/+archive/ubuntu/stable/+packages.
These packages are not recent!
Why has this link changed, and why not direct users to use the ppa?
I think the ppa is `ppa:minetestdevs/stable`.

**Comment by est31** [comment]
Ubuntu [is well aware](https://bugs.launchpad.net/ubuntu/+source/minetest/+bug/1491719) of the fact that there is a new minetest release. However, due to their own release freezing rules it won't appear in 15.10.
Their latest package is 0.4.12 which is fairly recent, and people should usually prefer using their own distro's package repository before trusting third parties.

What about linking to both? As in:
```
* Ubuntu / Linux Mint
* Ubuntu / Linux Mint (PPA)
```

**Comment by luk3yx** [comment]
There would need to be a clear warning that the PPA is up-to-date, but the other is not. Also mention the PPA name.

**Comment by est31** [comment]
There is already one, right above the list. The ppa name can be retrieved if clicking the link.
