### ISSUE TITLE
Language translations

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest.github.io#88]
How to translate Wiki? I can speak chinese.

**Comment by sfan5** [comment]
@Calinou

**Comment by Calinou** [comment]
If you want to participate in translating the wiki, post in [this forum topic](https://forum.minetest.net/viewtopic.php?f=3&t=10473) or just tell me your desired user name here.

Note that there already is an issue about translating the website itself: https://github.com/minetest/minetest.github.io/issues/26

**Comment by zaoqi** [comment]
@Calinou 
I desired wiki user name:zaoqi

**Comment by Calinou** [comment]
> @Calinou
> I desired wiki user name:zaoqi

Done, check your e-mail for the password.

**Comment by zaoqi** [comment]
@Calinou 
How to change "{{Languages}}"?
http://wiki.minetest.net/Main_Page/cn finish translation.
Chinese can't visit http://youtube.com/minetestc55 and http://c55.me/blog,so I deleted them.

**Comment by zaoqi** [comment]
http://c55.me/blog/
  Forbidden - Due to abuse, users from your country are not permitted to browse this site.
http://youtube.com/minetestc55(Nothing)

**Comment by MuhdNurHidayat** [comment]
I'm here just to clarify why those two links doesn't work

From what I see, http://c55.me/blog/ is apparently uses wordpress.com and not self-hosted
http://youtube.com/minetestc55 is a YouTube link

Both wordpress.com and YouTube (plus all Google services) are blocked by [The Great Firewall of China](https://en.wikipedia.org/wiki/Great_Firewall), that is the reason why people from China cannot visit them.

They still can visit it by using VPN, but be very careful that there are some places in China where using VPN is banned and they can be fined if found using it. For business people, make sure they applied VPN license and only use authorized VPN services approved by the government before using the VPN on the office internet connection, otherwise the whole office could be cut off internet and be fined with huge amount of money. (Foreigners in China are not affected, this only applies to the people of mainland China)
